import pygame

screenSize = width, height = 1600, 900

pygame.font.init()
usedFont = pygame.font.SysFont('Comic Sans MS', 30)

backgroundColour = 0, 0, 0
textColour = 255, 255, 255


#easy way to change the text
def ChangeRenderedText(text, choiceNames):
    screen.fill(backgroundColour)
    drawText(screen, text, textColour, pygame.Rect((0, 0), (1600, 900 - usedFont.size("Tg")[1])), usedFont, aa=False, bkg=None, choiceNames)

# draw some text into an area of a surface
# automatically wraps words
# returns any text that didn't get blitted
def drawText(surface, text, color, rect, font, aa=False, bkg=None, choiceNames):
    y = rect.top
    lineSpacing = -2

    # get the height of the font
    fontHeight = font.size("Tg")[1]

    while text:
        i = 1

        # determine if the row of text will be outside our area
        if y + fontHeight > rect.bottom:
            break

        # determine maximum width of line
        while font.size(text[:i])[0] < rect.width and i < len(text):
            i += 1

        # if we've wrapped the text, then adjust the wrap to the last word      
        if i < len(text): 
            i = text.rfind(" ", 0, i) + 1

        # render the line and blit it to the surface
        if bkg:
            image = font.render(text[:i], 1, color, bkg)
            image.set_colorkey(bkg)
        else:
            image = font.render(text[:i], aa, color)

        surface.blit(image, (rect.left, y))
        y += fontHeight + lineSpacing

        # remove the text we just blitted
        text = text[i:]
    return text


screen = pygame.display.set_mode(screenSize)
running = True
ChangeRenderedText('really long string AAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AAAAAAAAAAAAAAA AAAAAA AAA AAAAA AA')
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            
    
                                  
    pygame.display.flip()
pygame.display.quit()
pygame.quit()
